//
// Generated by Bluespec Compiler (build 38534dc)
//
// On Fri May 21 04:15:28 JST 2021
//
//
// Ports:
// Name                         I/O  size props
// outp                           O    16
// sel                            I     1
// a                              I    16
// b                              I    16
//
// Combinational paths from inputs to outputs:
//   (sel, a, b) -> outp
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMux(sel,
	     a,
	     b,
	     outp);
  // value method outp
  input  sel;
  input  [15 : 0] a;
  input  [15 : 0] b;
  output [15 : 0] outp;

  // signals for module outputs
  wire [15 : 0] outp;

  // value method outp
  assign outp = sel ? b : a ;
endmodule  // mkMux

